require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '\#.*' # ignore long comments

Style/AndOr:
  EnforcedStyle: conditionals

Metrics/BlockLength:
  Exclude: ['*.gemspec']

Metrics/MethodLength:
  Max: 25

Naming/FileName:
  Exclude: ['lib/resque-prioritize.rb']

Style/BlockDelimiters:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
